/** @format */

// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CustomSpinner } from "@/components/Modals/Modals";
import ReduxProvider from "@/lib/context/ReduxProvider";
import ThemeProviders from "@/lib/context/ThemeProviders";
import { HeroHighlight } from "@/components/ui/hero-highlight";
import { styles } from "./style";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeroHighlight>
          <ThemeProviders>
            <ReduxProvider>
              <CustomSpinner />
              <main className={`mx-auto max-w-[100rem]`}> {children}</main>
            </ReduxProvider>
          </ThemeProviders>
        </HeroHighlight>
      </body>
    </html>
  );
}
